import type { Contact } from '@prisma/client';
import { prisma } from '@/lib/db';
import { env } from '@/lib/env';
import { getEmail } from '@/lib/providers/email';
import { getOrgConfig } from '@/lib/config';
import { recordDealEvent, newCorrelationId } from '@/lib/deal/events';
import type { RoomContent } from './content';
import { assertProductionOnly } from '@/lib/safety/outbound';

/**
 * The message that carries a Deal Room.
 *
 * Everything in it is assembled from records. There is no template with a
 * paragraph of persuasion and a merge field, because that is what produces the
 * mail everyone in this industry deletes — and because a sentence we cannot
 * trace to a record is a sentence we cannot defend when somebody replies asking
 * where we got it.
 *
 * The greeting is generated by code rather than pulled from data, for a
 * specific reason the previous system learned expensively: "Hi ," and "Hi
 * Facilities Department Contact," both went out, and both told the recipient
 * exactly how much attention they were getting.
 */

export type Audience = 'VERIFIED_DECISION_MAKER' | 'NAMED_CONTACT' | 'PUBLISHED_PERSONAL' | 'GENERIC_INBOX';

export type AudienceChoice = {
  contact: Contact;
  audience: Audience;
  /** Why this address and not another. Stored with the message. */
  reason: string;
  /** Whether we hold a usable name for a greeting. */
  hasName: boolean;
  confidence: 'verified' | 'asserted' | 'inferred';
};

/**
 * Pick who to write to.
 *
 * The order is not a preference, it is a quality ladder. A verified
 * decision-maker is somebody a person established decides; a named contact is
 * somebody we hold a name and a role for; a published personal address is one
 * an individual owns; a generic inbox is a room with nobody's name on the door.
 * Sending to the last of those is sometimes right and always worse, so it
 * happens only where an operator has configured it.
 */
export function chooseAudience(
  contacts: Contact[],
  options: { allowGenericInbox: boolean },
): AudienceChoice | null {
  const emailable = contacts.filter(
    (c) => c.email
      && c.consentToEmail
      && c.email.includes('@')
      // A known-bad address is the one thing worse than no address: it costs a
      // send, damages the sending domain, and reports as delivered.
      && c.verificationStatus !== 'INVALID',
  );
  if (emailable.length === 0) return null;

  const named = (c: Contact) => Boolean(c.firstName?.trim()) && !isPlaceholderName(c.firstName);

  const verified = emailable.find((c) => c.isDecisionMaker && isVerified(c) && named(c));
  if (verified) {
    return {
      contact: verified,
      audience: 'VERIFIED_DECISION_MAKER',
      reason: 'A person established that this contact decides, and the address has been verified.',
      hasName: true,
      confidence: 'verified',
    };
  }

  const namedContact = emailable.find((c) => named(c) && !isGenericAddress(c.email!));
  if (namedContact) {
    return {
      contact: namedContact,
      audience: namedContact.isDecisionMaker ? 'NAMED_CONTACT' : 'PUBLISHED_PERSONAL',
      reason: namedContact.isDecisionMaker
        ? 'Named contact recorded as a decision-maker, though the address has not been verified.'
        : 'A named individual at the organisation. Not established as the person who decides.',
      hasName: true,
      confidence: isVerified(namedContact) ? 'verified' : 'asserted',
    };
  }

  const personal = emailable.find((c) => !isGenericAddress(c.email!));
  if (personal) {
    return {
      contact: personal,
      audience: 'PUBLISHED_PERSONAL',
      reason: 'A published individual address. We do not hold a usable name for it.',
      hasName: false,
      confidence: 'inferred',
    };
  }

  if (!options.allowGenericInbox) return null;

  return {
    contact: emailable[0],
    audience: 'GENERIC_INBOX',
    reason: 'Only a general inbox is on file. Sent because the organisation has enabled generic-inbox fallback.',
    hasName: false,
    confidence: 'inferred',
  };
}

/**
 * Verified by somebody, by either route.
 *
 * `INVALID` is deliberately not a form of verification: a bounced address is
 * the most confirmed a record can be and the least sendable.
 */
function isVerified(contact: Contact): boolean {
  return contact.verificationStatus === 'VERIFIED_BY_CALL'
    || contact.verificationStatus === 'VERIFIED_BY_SOURCE';
}

/** info@, sales@ and friends: a room, not a person. */
export function isGenericAddress(email: string): boolean {
  const local = email.split('@')[0]?.toLowerCase() ?? '';
  return [
    'info', 'sales', 'contact', 'hello', 'admin', 'office', 'enquiries', 'inquiries',
    'support', 'help', 'team', 'mail', 'general', 'reception', 'purchasing', 'accounts',
  ].includes(local);
}

/**
 * Names that are not names.
 *
 * Directory imports are full of these. Greeting somebody as "Owner" is worse
 * than not greeting them by name at all, because it advertises that a machine
 * filled the field.
 */
function isPlaceholderName(name: string | null | undefined): boolean {
  if (!name) return true;
  const trimmed = name.trim().toLowerCase();
  if (trimmed.length < 2) return true;
  return [
    'owner', 'manager', 'contact', 'admin', 'info', 'n/a', 'na', 'unknown',
    'director', 'purchasing', 'facilities', 'the', 'team', 'department',
  ].includes(trimmed);
}

/**
 * A greeting that is never wrong.
 *
 * Generated here rather than templated, so there is exactly one place where a
 * missing first name turns into "Hello," instead of "Hi ,". The plain version
 * is not a degraded fallback — it is a perfectly ordinary way to open a letter,
 * and it is what a person would write.
 */
export function greeting(choice: AudienceChoice): string {
  if (!choice.hasName) return 'Hello,';
  const first = choice.contact.firstName.trim().split(/\s+/)[0];
  return `Hi ${first},`;
}

// ---------------------------------------------------------------------------
// The message
// ---------------------------------------------------------------------------

export type DraftedEmail = {
  subject: string;
  body: string;
  /** Every claim in the body, and the record it came from. */
  grounding: string[];
  /** Reasons this should not be sent as drafted. Non-empty blocks autonomous send. */
  blockers: string[];
};

/**
 * Draft the message from the room's own snapshot.
 *
 * Nothing is invented here, and that constraint produces the shape of it: a
 * dated observation, what we think it means labelled as what we think, the one
 * thing we are asking for, and the link. If the room has no dated event behind
 * it there is no first line to write, and this says so rather than reaching for
 * a generic opener.
 */
export function draftRoomEmail(input: {
  content: RoomContent;
  choice: AudienceChoice;
  url: string;
  senderName: string;
}): DraftedEmail {
  const { content, choice } = input;
  const grounding: string[] = [];
  const blockers: string[] = [];

  if (!content.why) {
    blockers.push('There is no dated event behind this room, so the opening line would be an assertion with nothing under it.');
  }
  if (content.tooThinToSend) {
    blockers.push(...content.thinReasons);
  }
  if (choice.audience === 'GENERIC_INBOX') {
    grounding.push('Sent to a general inbox: nobody specific is being addressed, and the message says so.');
  }

  const lines: string[] = [greeting(choice), ''];

  if (content.why) {
    lines.push(
      `${content.why.text} — dated ${content.why.eventDate}, from ${content.why.source}.`,
      '',
    );
    grounding.push(`Opening line from the demand event dated ${content.why.eventDate}.`);
  }

  // The one inference, stated as one. A prospect can correct an assumption
  // they can see; they cannot correct one dressed up as a finding.
  const firstOurs = content.sections.flatMap((s) => s.ours).find(Boolean);
  if (firstOurs) {
    lines.push(`We think that means ${lowerFirst(firstOurs)} We may have that wrong.`, '');
    grounding.push('The inference is labelled as ours in the body, matching the room.');
  }

  const questions = content.sections.flatMap((s) => s.questions).slice(0, 2);
  if (questions.length > 0) {
    lines.push('What we cannot tell from the record:', ...questions.map((q) => `  - ${q}`), '');
    grounding.push(`${questions.length} open question(s) taken from the requirement gaps.`);
  }

  lines.push(
    content.proofStep.ask,
    `That commits you to: ${lowerFirst(content.proofStep.commitment)}`,
    '',
    'The detail, and where each part of it came from:',
    input.url,
    '',
    'If this is not you, or not relevant, replying with that is genuinely useful and we will stop.',
    '',
    input.senderName,
  );
  grounding.push(`The ask is the recommended proof step (${content.proofStep.kind}).`);

  const subject = content.why
    ? `${content.organisation} — ${truncate(content.why.text, 60)}`
    : `${content.organisation} — a question about ${content.route.toLowerCase()}`;

  return { subject, body: lines.join('\n'), grounding, blockers };
}

// ---------------------------------------------------------------------------
// Sending
// ---------------------------------------------------------------------------

/**
 * Put a room in front of a prospect.
 *
 * Refuses rather than throws, because the caller is an API route that has
 * already marked the room sent and needs to report what happened rather than
 * unwind. Every refusal names the specific reason, so nothing here can fail
 * silently and look like a delivery.
 */
export async function sendRoomEmail(options: {
  orgId: string;
  roomId: string;
  contactId: string;
  senderId?: string | null;
}): Promise<{ sent: boolean; reason?: string; messageId?: string; audience?: Audience }> {
  // A deal room built on a sandbox opportunity is a page about an invented
  // company. Delivering it is refused before the room is even loaded.
  await assertProductionOnly(
    { roomId: options.roomId, contactId: options.contactId },
    'delivering a deal room',
  );

  const room = await prisma.dealRoom.findFirst({
    where: { id: options.roomId, orgId: options.orgId },
    include: { route: { select: { id: true } } },
  });
  if (!room) return { sent: false, reason: 'That room is not on this account.' };

  const contact = await prisma.contact.findFirst({
    where: { id: options.contactId, orgId: options.orgId },
  });
  if (!contact) return { sent: false, reason: 'That contact is not on this account.' };
  if (!contact.email) return { sent: false, reason: 'No email address on that contact.' };
  if (!contact.consentToEmail) return { sent: false, reason: 'That contact has withdrawn email consent.' };

  const suppressed = await prisma.suppressionEntry.findFirst({
    where: {
      orgId: options.orgId,
      contactId: options.contactId,
      scope: { in: ['DO_NOT_EMAIL', 'DO_NOT_CONTACT'] },
    },
  });
  if (suppressed) return { sent: false, reason: `Suppressed for email: ${suppressed.reason}` };

  const config = await getOrgConfig(options.orgId);
  const choice = chooseAudience([contact], { allowGenericInbox: config.outreachRules.allowGenericInboxFallback });
  if (!choice) {
    return {
      sent: false,
      reason: 'Only a general inbox is available and generic-inbox fallback is switched off for this organisation.',
    };
  }

  const content = room.content as unknown as RoomContent;
  const url = `${env().APP_URL.replace(/\/$/, '')}/room/${room.token}`;
  const sender = await prisma.user.findFirst({
    where: { id: options.senderId ?? undefined, orgId: options.orgId },
    select: { name: true },
  });

  const draft = draftRoomEmail({
    content,
    choice,
    url,
    senderName: sender?.name ?? 'The team',
  });

  if (draft.blockers.length > 0) {
    return { sent: false, reason: `Not sent: ${draft.blockers.join(' ')}` };
  }

  const result = await getEmail().send({ to: contact.email, subject: draft.subject, body: draft.body });

  // Read back what the provider actually accepted rather than trusting the
  // call returning. A 200 with no message id is not a delivery, and treating
  // it as one is how a campaign reports success into an empty mailbox.
  if (!result.providerMessageId) {
    return { sent: false, reason: 'The email provider accepted the request but returned no message id, so nothing can be confirmed.' };
  }

  // Nothing left the building. Recorded as queued with the reason attached, so
  // it is visible work with a way back rather than a message the system
  // believes it sent — and never marked AWAITING_RESPONSE, because nobody is
  // going to respond to something that was never delivered.
  if (result.status === 'suppressed') {
    await prisma.message.create({
      data: {
        orgId: options.orgId,
        routeId: room.routeId,
        contactId: contact.id,
        companyId: contact.companyId,
        senderId: options.senderId ?? null,
        channel: 'EMAIL',
        direction: 'outbound',
        status: 'QUEUED',
        subject: draft.subject,
        body: draft.body,
        provider: getEmail().name,
        providerMessageId: result.providerMessageId,
        sentAt: null,
        outcome: 'UNDELIVERABLE',
        failureReason: result.reason ?? 'No transport accepted this message.',
      },
    });
    return { sent: false, reason: result.reason ?? 'No email transport is configured, so nothing was sent.' };
  }

  const message = await prisma.message.create({
    data: {
      orgId: options.orgId,
      routeId: room.routeId,
      contactId: contact.id,
      companyId: contact.companyId,
      senderId: options.senderId ?? null,
      channel: 'EMAIL',
      direction: 'outbound',
      status: 'SENT',
      subject: draft.subject,
      body: draft.body,
      provider: getEmail().name,
      providerMessageId: result.providerMessageId,
      sentAt: new Date(),
      outcome: 'AWAITING_RESPONSE',
      costCents: config.outreachCosts.emailPerMessage * 100,
    },
  });

  await prisma.$transaction(async (tx) => {
    await recordDealEvent(tx, {
      orgId: options.orgId,
      routeId: room.routeId,
      kind: 'room.emailed',
      actorId: options.senderId,
      subjectType: 'RouteQuote',
      subjectId: room.id,
      // Audience and confidence are kept with the send, so a reply rate can
      // later be read per audience type rather than in one meaningless average.
      summary: `Deal room emailed to a ${choice.audience.toLowerCase().replace(/_/g, ' ')}.`,
      after: {
        audience: choice.audience,
        confidence: choice.confidence,
        hasName: choice.hasName,
        providerMessageId: result.providerMessageId,
      },
      evidence: choice.reason,
      confidence: choice.confidence,
      correlationId: newCorrelationId(),
    });
  });

  return { sent: true, messageId: message.id, audience: choice.audience };
}

function lowerFirst(text: string): string {
  return text.charAt(0).toLowerCase() + text.slice(1);
}

function truncate(text: string, max: number): string {
  return text.length <= max ? text : `${text.slice(0, max - 1).trimEnd()}…`;
}
